### ISSUE TITLE
Request: Add a license

### ISSUE THREAD

**Issue by nicoburns** [chearon/dropflow#4]
This project looks great, but it seems to be missing a license. Would you be willing to add an explicit licence so that people can know when and where they can use it? My preferred licence would be dual MIT/Apache 2.0 but obviously you can and should choose whichever license you see fit.

**Comment by chearon** [comment]
I put MIT in the `package.json`, but I should add a `LICENSE` file, yeah. I picked MIT because I don't mind if people need to change it in closed-source. What would be the difference if I switched to MIT/Apache 2.0? I'm not learning much by googling it and my understanding of licenses is limited, but I'm open to that.

**Comment by nicoburns** [comment]
Ah, I didn't see the license in `package.json`.

There's not a lot of difference between the MIT and Apache 2.0 licenses (note that licensing under `MIT/Apache 2.0` basically means that you grant a licence to the code separately under each license and users may choose one or both). The main difference being that Apache 2.0 also grants a patent license to any patents you may have on the source code. Which may well not be relevant to this code base. Licensing under both is standard in the Rust ecosystem for maximum flexibility which was the reason for my suggestion.

^ That's the long answer. But if you just stuck a MIT license file in the repo I'd be pretty happy :)

**Comment by chearon** [comment]
Thank you for that! I think MIT makes sense.
