### ISSUE TITLE
Khmer Text Overlapping

### ISSUE THREAD

**Issue by seanghay** [chearon/dropflow#9]
This project is really amazing and challenging! I'm amazed that you've pulled it off!

I encountered an issue with my language while testing the demo. My guess is that the engine doesn't understand how to break Khmer text.

## Render
![image](https://github.com/chearon/dropflow/assets/15277233/477579bb-dc15-424f-8e16-d8b5facff4b5)

## Content
<p>រស់ សេរីសុទ្ធា កេីតនៅថ្ងៃទី០៦ ខែ វិច្ឆិកា ឆ្នាំ ១៩៤៧ នាងមានកំណើតនៅក្នុងគ្រួសារកសិករក្រីក្រមួយ ក្នុង ខេត្តបាត់ដំបង ។ សុធា មានឪពុកឈ្មោះ រស់ ប៊ុន និង ម្ដាយឈ្មោះ ណាត់ សាមៀន និង មានបងប្អូនចំនួន ៥ នាក់ ប្រុស១នាក់ ស្រី៤នាក់ (បច្ចុប្បន្នស្លាប់ទាំងអស់) បងស្រីទី១ ឈ្មោះ រស់ សាបឿន, បងស្រីទី២ ឈ្មោះ រស់សាបឿត, បងប្រុសទី៣ ឈ្មោះ រស់ សុគន្ធ, ទី៤សុធាផ្ទាល់ ឈ្មោះ រស់ សេរីសុទ្ធា និង ទី៥ប្អូនស្រី ឈ្មោះ រស់ សេរីសោភ័ណ, សុធា នាងបានចូលសិក្សា ថ្នាក់អនុវិទ្យាល័យនេតយ៉ង់ ក្នុងខេត្តបាត់ដំបង ។ ទេពកោសល្យ របស់សុធា បានរកឃើញនៅអាយុ ១៣ ឆ្នាំ ពេលដែលនាងបានច្រៀងចម្រៀង ប្រចាំថ្នាក់អនុវិទ្យាល័យ ក្នុងឆ្នាំ ១៩៦០ សិស្សរួមថ្នាក់ និងលោកគ្រូ អ្នកគ្រូ តែងតែសរសើរទឹកដមសម្លេងដ៏ច្បាស់ ស្រទន់ និង ខ្លាំងរបស់ សុធា ដែលប្រៀបបាននិង សម្លេងរណ្ដំរបស់សត្វរៃ ហើយសុធា ត្រូវបានគេដាក់ឈ្មោះហៅក្រៅពេលនោះថា (អារៃ) ដោយឪពុករបស់សុធា មើលឃើញពីទេពកោសល្យផ្នែកចម្រៀងដូចនេះ ក៏បាននាំសុធា ដើរច្រៀងតាមពិធីមង្គលការ និង ភោជនីយដ្ឋានផ្សេងៗ ក្នុងខេត្តបាត់ដំបង ។</p>

**Comment by chearon** [comment]
Thanks for testing out Khmer! Dropflow can't use system fonts, and the demo only has Roboto loaded right now. So the layout engine is getting tofu, and the paint backend (`<canvas>`) _does_ use system fonts. That's why you're seeing the gaps. Khmer should work correctly when a font is registered though.

Ideally I'd update the demo to have the top 100 languages or so, but if that impacts performance, I'll have to add a language selector. The long-term solution is to have it lazily download fonts, which is pretty high on my list of things to do.

**Comment by seanghay** [comment]
![image](https://github.com/chearon/dropflow/assets/15277233/4d40aaa5-9591-496b-adc0-4966c57e8c30)

It works now with Noto Sans Khmer loaded. Thanks!
